n = input('Digite algo: ')
print('O tipo primitivo é:', type(n))
print('É numérico?', n.isnumeric())
print('É alfabético?', n.isalpha())
print('É alfanumérico?', n.isalnum())
print('Só tem espaços?', n.isspace())
print('Está em maiúsculas?', n.isupper())
print('Está em minúsculas?', n.islower())
print('Está capitalizada?', n.istitle())
